-- require("impatient")
require("tesohh.plugins-setup")
require("tesohh.core.options")
require("tesohh.core.keymaps")
require("tesohh.core.colorscheme")

require("tesohh.plugins.comment")
require("tesohh.plugins.nvim-tree")
require("tesohh.plugins.feline")
require("tesohh.plugins.nvim-cmp")
require("tesohh.plugins.lsp.mason")
require("tesohh.plugins.lsp.lspsaga")
require("tesohh.plugins.lsp.lspconfig")
require("tesohh.plugins.lsp.null-ls")
require("tesohh.plugins.autopairs")
require("tesohh.plugins.treesitter")
require("tesohh.plugins.gitsigns")
require("tesohh.plugins.bufferline")
require("tesohh.plugins.dashboard")
require("tesohh.plugins.trouble")
require("tesohh.plugins.nvterm")
